https://raw.githubusercontent.com/MitwRdam/MakeAIWork/main/practica/week3/sql/notebook/sql.ipynb<div>
    <img src='../pics/banner.PNG'/>
</div>
<div>
    <img width="10%" height="10%" src='../pics/python-programming.png'/>
    <img src='../pics/miw.PNG'/>
</div>
<div>
    <em>Author: Jeroen Boogaard</em>
</div>

<h1>Practicum SQL </h1>

<h2>Imports<h2>

In [9]:
from os import system as sys
sys('pip install pysqlite3 --upgrade pip')

1

In [10]:
from matplotlib import pyplot as plt
from matplotlib_venn import venn2, venn3
from PIL import Image
import pandas as pd
import sqlite3

<h2>Extract, Transform and Load</h2>

<h3>Extract</h3>

In [11]:
# https://raw.githubusercontent.com/ajturner/acetate/master/places/Countries-Europe.csv
eurCsvFile = "../csv/countries_europe.csv"
euCsvFile = "../csv/countries_europe.csv"

 # Create Pandas DataFrames
europeDF = pd.read_csv(eurCsvFile)
euDF = pd.read_csv(euCsvFile)
print(europeDF)
print(euDF)

    zoom                    name  abbreviation Code  ISO numeric  \
0      3                 Ukraine          Ukr.  UKR          804
1      3                  France           Fr.  FRA          250
2      3                   Spain         Spain  ESP          724
3      3                  Sweden          Swe.  SWE          752
4      3                 Germany          Ger.  DEU          276
5      3                 Finland          Fin.  FIN          246
6      3                  Norway          Nor.  NOR          578
7      3                  Poland          Pol.  POL          616
8      3                   Italy         Italy  ITA          380
9      3          United Kingdom          U.K.  GBR          826
10     3                 Romania          Rom.  ROU          642
11     3                 Belarus         Bela.  BLR          112
12     3                  Greece          Grc.  GRC          300
13     3                Bulgaria          Blg.  BGR          100
14     3                 Iceland          Ice.  ISL          352
15     3                Portugal         Port.  PRT          620
16     3          Czech Republic    Czech Rep.  CZE          203
17     3                 Denmark          Den.  DNK          208
18     4                 Hungary         Hung.  HUN          348
19     4                  Serbia         Serb.  SRB          688
20     4                 Austria          Aus.  AUT           40
21     4                 Ireland          Ire.  IRL          372
22     4               Lithuania         Lith.  LTU          440
23     4                  Latvia          Lat.  LVA          428
24     4                 Croatia          Cro.  HRV          191
25     4  Bosnia and Herzegovina          Bos.  BIH           70
26     4                Slovakia         Slvk.  SVK          703
27     4                 Estonia          Est.  EST          233
28     4             Netherlands         Neth.  NLD          528
29     4             Switzerland        Switz.  CHE          756
30     4                 Moldova          Mol.  MDA          498
31     4                 Belgium          Bel.  BEL           56
32     4                 Albania          Alb.  ALB            8
33     4               Macedonia          Mac.  MKD          807
34     4                Slovenia         Slvn.  SVN          705
35     4              Montenegro         Mont.  MNE          499
36     4                  Cyprus          Cyp.  CYP          196
37     4              Luxembourg          Lux.  LUX          442
38     4               Faroe Is.      Far. Is.  FRO          234
39     4                 Andorra          And.  AND           20
40     4                   Malta         Malta  MLT          470
41     4           Liechtenstein        Liech.  LIE          438
42     4                Guernsey        Guern.  GGY          831
43     4              San Marino       S. Mar.  SMR          674
44     4               Gibraltar          Gib.  GIB          292
45     4                  Monaco        Monaco  MCO          492
46     4            Vatican City  Vatican City  VAT          336

    land area km  population  latitude  longitude continent
0       603700.0    45415596     49.00      32.00        eu
1       547030.0    64768389     46.00       2.00        eu
2       504782.0    46505963     40.00      -4.00        eu
3       449964.0     9045000     62.00      15.00        eu
4       357021.0    82369000     51.50      10.50        eu
5       337030.0     5244000     64.00      26.00        eu
6       324220.0     4907000     62.00      10.00        eu
7       312685.0    38500000     52.00      20.00        eu
8       301230.0    58145000     42.83      12.83        eu
9       244820.0    62348447     54.90      -3.12        eu
10      237500.0    21959278     46.00      25.00        eu
11      207600.0     9685000     53.00      28.00        eu
12      131940.0    11000000     39.00      22.00        eu
13      110910.0     7148785     43.00      25.00        eu
14      103000.0      308910     65.00     -18.00        eu
15       92391.0    10676000     39.50      -8.00        eu
16       78866.0    10476000     49.75      15.00        eu
17       43094.0     5484000     56.00      10.00        eu
18       93030.0     9930000     47.00      20.00        eu
19       88361.0     7344847     44.82      20.46        eu
20       83858.0     8205000     47.33      13.33        eu
21       70280.0     4622917     53.00      -8.00        eu
22       65200.0     3565000     56.00      24.00        eu
23       64589.0     2217969     57.00      25.00        eu
24       56542.0     4491000     45.17      15.50        eu
25       51129.0     4590000     44.25      17.83        eu
26       48845.0     5455000     48.67      19.50        eu
27       45226.0     1291170     59.00      26.00        eu
28       41526.0    16645000     52.50       5.75        eu
29       41290.0     7581000     47.00       8.01        eu
30       33843.0     4324000     47.00      29.00        eu
31       30510.0    10403000     50.83       4.00        eu
32       28748.0     2986952     41.00      20.00        eu
33       25333.0     2061000     41.83      22.00        eu
34       20273.0     2007000     46.25      15.17        eu
35       14026.0      666730     43.50      19.30        eu
36        9250.0     1102677     35.00      33.00      asia
37        2586.0      497538     49.75       6.17        eu
38        1399.0       48228     62.00      -7.00        eu
39         468.0       84000     42.50       1.50        eu
40         316.0      403000     35.92      14.43        eu
41         160.0       35000     47.17       9.53        eu
42          78.0       65228     49.58      -2.33        eu
43          61.2       31477     43.93      12.42        eu
44           6.5       27884     36.13      -5.35        eu
45           2.0       32965     43.73       7.42        eu
46           0.4         921     41.90      12.45        eu
    zoom                    name  abbreviation Code  ISO numeric  \
0      3                 Ukraine          Ukr.  UKR          804
1      3                  France           Fr.  FRA          250
2      3                   Spain         Spain  ESP          724
3      3                  Sweden          Swe.  SWE          752
4      3                 Germany          Ger.  DEU          276
5      3                 Finland          Fin.  FIN          246
6      3                  Norway          Nor.  NOR          578
7      3                  Poland          Pol.  POL          616
8      3                   Italy         Italy  ITA          380
9      3          United Kingdom          U.K.  GBR          826
10     3                 Romania          Rom.  ROU          642
11     3                 Belarus         Bela.  BLR          112
12     3                  Greece          Grc.  GRC          300
13     3                Bulgaria          Blg.  BGR          100
14     3                 Iceland          Ice.  ISL          352
15     3                Portugal         Port.  PRT          620
16     3          Czech Republic    Czech Rep.  CZE          203
17     3                 Denmark          Den.  DNK          208
18     4                 Hungary         Hung.  HUN          348
19     4                  Serbia         Serb.  SRB          688
20     4                 Austria          Aus.  AUT           40
21     4                 Ireland          Ire.  IRL          372
22     4               Lithuania         Lith.  LTU          440
23     4                  Latvia          Lat.  LVA          428
24     4                 Croatia          Cro.  HRV          191
25     4  Bosnia and Herzegovina          Bos.  BIH           70
26     4                Slovakia         Slvk.  SVK          703
27     4                 Estonia          Est.  EST          233
28     4             Netherlands         Neth.  NLD          528
29     4             Switzerland        Switz.  CHE          756
30     4                 Moldova          Mol.  MDA          498
31     4                 Belgium          Bel.  BEL           56
32     4                 Albania          Alb.  ALB            8
33     4               Macedonia          Mac.  MKD          807
34     4                Slovenia         Slvn.  SVN          705
35     4              Montenegro         Mont.  MNE          499
36     4                  Cyprus          Cyp.  CYP          196
37     4              Luxembourg          Lux.  LUX          442
38     4               Faroe Is.      Far. Is.  FRO          234
39     4                 Andorra          And.  AND           20
40     4                   Malta         Malta  MLT          470
41     4           Liechtenstein        Liech.  LIE          438
42     4                Guernsey        Guern.  GGY          831
43     4              San Marino       S. Mar.  SMR          674
44     4               Gibraltar          Gib.  GIB          292
45     4                  Monaco        Monaco  MCO          492
46     4            Vatican City  Vatican City  VAT          336

    land area km  population  latitude  longitude continent
0       603700.0    45415596     49.00      32.00        eu
1       547030.0    64768389     46.00       2.00        eu
2       504782.0    46505963     40.00      -4.00        eu
3       449964.0     9045000     62.00      15.00        eu
4       357021.0    82369000     51.50      10.50        eu
5       337030.0     5244000     64.00      26.00        eu
6       324220.0     4907000     62.00      10.00        eu
7       312685.0    38500000     52.00      20.00        eu
8       301230.0    58145000     42.83      12.83        eu
9       244820.0    62348447     54.90      -3.12        eu
10      237500.0    21959278     46.00      25.00        eu
11      207600.0     9685000     53.00      28.00        eu
12      131940.0    11000000     39.00      22.00        eu
13      110910.0     7148785     43.00      25.00        eu
14      103000.0      308910     65.00     -18.00        eu
15       92391.0    10676000     39.50      -8.00        eu
16       78866.0    10476000     49.75      15.00        eu
17       43094.0     5484000     56.00      10.00        eu
18       93030.0     9930000     47.00      20.00        eu
19       88361.0     7344847     44.82      20.46        eu
20       83858.0     8205000     47.33      13.33        eu
21       70280.0     4622917     53.00      -8.00        eu
22       65200.0     3565000     56.00      24.00        eu
23       64589.0     2217969     57.00      25.00        eu
24       56542.0     4491000     45.17      15.50        eu
25       51129.0     4590000     44.25      17.83        eu
26       48845.0     5455000     48.67      19.50        eu
27       45226.0     1291170     59.00      26.00        eu
28       41526.0    16645000     52.50       5.75        eu
29       41290.0     7581000     47.00       8.01        eu
30       33843.0     4324000     47.00      29.00        eu
31       30510.0    10403000     50.83       4.00        eu
32       28748.0     2986952     41.00      20.00        eu
33       25333.0     2061000     41.83      22.00        eu
34       20273.0     2007000     46.25      15.17        eu
35       14026.0      666730     43.50      19.30        eu
36        9250.0     1102677     35.00      33.00      asia
37        2586.0      497538     49.75       6.17        eu
38        1399.0       48228     62.00      -7.00        eu
39         468.0       84000     42.50       1.50        eu
40         316.0      403000     35.92      14.43        eu
41         160.0       35000     47.17       9.53        eu
42          78.0       65228     49.58      -2.33        eu
43          61.2       31477     43.93      12.42        eu
44           6.5       27884     36.13      -5.35        eu
45           2.0       32965     43.73       7.42        eu
46           0.4         921     41.90      12.45        eu

<h3>Transform</h3>

<h3>Exercise 1</h3>
<h4>Gegeven</h4>

In [12]:
benelux = {"Belgium", "Netherlands", "Luxembourg"}
nordics = {"Denmark", "Finland", "Iceland", "Norway"}
baltics = {"Estonia", "Latvia", "Lithuania"}

<h4>Gevraagd</h4>
<ol>
    <li>Voeg de kolom <u>groups</u> toe aan de dataset <u>europeDF</u> met daarin de groep waartoe een land behoort volgens bovenstaande sets</li>
    <li>Ga na of er nog meer landengroepen zijn binnen Europa en voeg die ook toe</li>
    <li>Sla deze verrijkte dataset op in een nieuw CSV bestand</li>
</ol>

<h4>Oplossing</h4>

In [13]:
# Oplossing
def group_add (row):
    if row["name"] in {"Belgium", "Netherlands", "Luxembourg"}:
        return "benelux"
    if row["name"] in {"Denmark", "Finland", "Iceland", "Norway"}:
        return "nordics"
    if row["name"] in {"Estonia", "Latvia", "Lithuania"}:
        return "baltics"
    return "others"
europeDF['groups'] = europeDF.apply (lambda row: group_add(row), axis=1)
europeDF.to_csv("C:/Users/Lenovo/MakeAIWork1/practica/week3/sql/csv/groups.csv")

display(europeDF)

,zoom,name,abbreviation,Code,ISO numeric,land area km,population,latitude,longitude,continent,groups
0,3,Ukraine,Ukr.,UKR,804,603700.0,45415596,49.00,32.00,eu,others
1,3,France,Fr.,FRA,250,547030.0,64768389,46.00,2.00,eu,others
2,3,Spain,Spain,ESP,724,504782.0,46505963,40.00,-4.00,eu,others
3,3,Sweden,Swe.,SWE,752,449964.0,9045000,62.00,15.00,eu,others
4,3,Germany,Ger.,DEU,276,357021.0,82369000,51.50,10.50,eu,others
5,3,Finland,Fin.,FIN,246,337030.0,5244000,64.00,26.00,eu,nordics
6,3,Norway,Nor.,NOR,578,324220.0,4907000,62.00,10.00,eu,nordics
7,3,Poland,Pol.,POL,616,312685.0,38500000,52.00,20.00,eu,others
8,3,Italy,Italy,ITA,380,301230.0,58145000,42.83,12.83,eu,others
9,3,United Kingdom,U.K.,GBR,826,244820.0,62348447,54.90,-3.12,eu,others
10,3,Romania,Rom.,ROU,642,237500.0,21959278,46.00,25.00,eu,others
11,3,Belarus,Bela.,BLR,112,207600.0,9685000,53.00,28.00,eu,others
12,3,Greece,Grc.,GRC,300,131940.0,11000000,39.00,22.00,eu,others
13,3,Bulgaria,Blg.,BGR,100,110910.0,7148785,43.00,25.00,eu,others
14,3,Iceland,Ice.,ISL,352,103000.0,308910,65.00,-18.00,eu,nordics
15,3,Portugal,Port.,PRT,620,92391.0,10676000,39.50,-8.00,eu,others
16,3,Czech Republic,Czech Rep.,CZE,203,78866.0,10476000,49.75,15.00,eu,others
17,3,Denmark,Den.,DNK,208,43094.0,5484000,56.00,10.00,eu,nordics
18,4,Hungary,Hung.,HUN,348,93030.0,9930000,47.00,20.00,eu,others
19,4,Serbia,Serb.,SRB,688,88361.0,7344847,44.82,20.46,eu,others
20,4,Austria,Aus.,AUT,40,83858.0,8205000,47.33,13.33,eu,others
21,4,Ireland,Ire.,IRL,372,70280.0,4622917,53.00,-8.00,eu,others
22,4,Lithuania,Lith.,LTU,440,65200.0,3565000,56.00,24.00,eu,baltics
23,4,Latvia,Lat.,LVA,428,64589.0,2217969,57.00,25.00,eu,baltics
24,4,Croatia,Cro.,HRV,191,56542.0,4491000,45.17,15.50,eu,others
25,4,Bosnia and Herzegovina,Bos.,BIH,70,51129.0,4590000,44.25,17.83,eu,others
26,4,Slovakia,Slvk.,SVK,703,48845.0,5455000,48.67,19.50,eu,others
27,4,Estonia,Est.,EST,233,45226.0,1291170,59.00,26.00,eu,baltics
28,4,Netherlands,Neth.,NLD,528,41526.0,16645000,52.50,5.75,eu,benelux
29,4,Switzerland,Switz.,CHE,756,41290.0,7581000,47.00,8.01,eu,others
30,4,Moldova,Mol.,MDA,498,33843.0,4324000,47.00,29.00,eu,others
31,4,Belgium,Bel.,BEL,56,30510.0,10403000,50.83,4.00,eu,benelux
32,4,Albania,Alb.,ALB,8,28748.0,2986952,41.00,20.00,eu,others
33,4,Macedonia,Mac.,MKD,807,25333.0,2061000,41.83,22.00,eu,others
34,4,Slovenia,Slvn.,SVN,705,20273.0,2007000,46.25,15.17,eu,others
35,4,Montenegro,Mont.,MNE,499,14026.0,666730,43.50,19.30,eu,others
36,4,Cyprus,Cyp.,CYP,196,9250.0,1102677,35.00,33.00,asia,others
37,4,Luxembourg,Lux.,LUX,442,2586.0,497538,49.75,6.17,eu,benelux
38,4,Faroe Is.,Far. Is.,FRO,234,1399.0,48228,62.00,-7.00,eu,others
39,4,Andorra,And.,AND,20,468.0,84000,42.50,1.50,eu,others
40,4,Malta,Malta,MLT,470,316.0,403000,35.92,14.43,eu,others
41,4,Liechtenstein,Liech.,LIE,438,160.0,35000,47.17,9.53,eu,others
42,4,Guernsey,Guern.,GGY,831,78.0,65228,49.58,-2.33,eu,others
43,4,San Marino,S. Mar.,SMR,674,61.2,31477,43.93,12.42,eu,others
44,4,Gibraltar,Gib.,GIB,292,6.5,27884,36.13,-5.35,eu,others
45,4,Monaco,Monaco,MCO,492,2.0,32965,43.73,7.42,eu,others
46,4,Vatican City,Vatican City,VAT,336,0.4,921,41.90,12.45,eu,others

<h3>Load</h3>

<p>Maak een lege database</p>

In [28]:
sys('sqlite3 ../db/europe.db "VACUUM;"')

0

In [29]:
sys('sqlite3 ../db/data.db "VACUUM;"')

0

In [15]:
# Connect to SQLite database
dbConnection = sqlite3.connect('../db/europe.db')

<p>Maak tabellen o.b.v. de dataset</p>

In [16]:
europeDF.to_sql('countries', dbConnection, if_exists='replace', index = False)
euDF.to_sql('eu', dbConnection, if_exists='replace', index = False)

47

In [17]:
dbCursor = dbConnection.cursor()

query = """
    SELECT *
    FROM countries
    INNER JOIN eu
    ON countries.Code = eu.Code
"""

result = dbCursor.execute(query).fetchall()
print(result)
print(type(result))

[(3, 'Ukraine', 'Ukr.', 'UKR', 804, 603700.0, 45415596, 49.0, 32.0, 'eu', 'others', 3, 'Ukraine', 'Ukr.', 'UKR', 804, 603700.0, 45415596, 49.0, 32.0, 'eu'), (3, 'France', 'Fr.', 'FRA', 250, 547030.0, 64768389, 46.0, 2.0, 'eu', 'others', 3, 'France', 'Fr.', 'FRA', 250, 547030.0, 64768389, 46.0, 2.0, 'eu'), (3, 'Spain', 'Spain', 'ESP', 724, 504782.0, 46505963, 40.0, -4.0, 'eu', 'others', 3, 'Spain', 'Spain', 'ESP', 724, 504782.0, 46505963, 40.0, -4.0, 'eu'), (3, 'Sweden', 'Swe.', 'SWE', 752, 449964.0, 9045000, 62.0, 15.0, 'eu', 'others', 3, 'Sweden', 'Swe.', 'SWE', 752, 449964.0, 9045000, 62.0, 15.0, 'eu'), (3, 'Germany', 'Ger.', 'DEU', 276, 357021.0, 82369000, 51.5, 10.5, 'eu', 'others', 3, 'Germany', 'Ger.', 'DEU', 276, 357021.0, 82369000, 51.5, 10.5, 'eu'), (3, 'Finland', 'Fin.', 'FIN', 246, 337030.0, 5244000, 64.0, 26.0, 'eu', 'nordics', 3, 'Finland', 'Fin.', 'FIN', 246, 337030.0, 5244000, 64.0, 26.0, 'eu'), (3, 'Norway', 'Nor.', 'NOR', 578, 324220.0, 4907000, 62.0, 10.0, 'eu', 'nordics', 3, 'Norway', 'Nor.', 'NOR', 578, 324220.0, 4907000, 62.0, 10.0, 'eu'), (3, 'Poland', 'Pol.', 'POL', 616, 312685.0, 38500000, 52.0, 20.0, 'eu', 'others', 3, 'Poland', 'Pol.', 'POL', 616, 312685.0, 38500000, 52.0, 20.0, 'eu'), (3, 'Italy', 'Italy', 'ITA', 380, 301230.0, 58145000, 42.83, 12.83, 'eu', 'others', 3, 'Italy', 'Italy', 'ITA', 380, 301230.0, 58145000, 42.83, 12.83, 'eu'), (3, 'United Kingdom', 'U.K.', 'GBR', 826, 244820.0, 62348447, 54.9, -3.12, 'eu', 'others', 3, 'United Kingdom', 'U.K.', 'GBR', 826, 244820.0, 62348447, 54.9, -3.12, 'eu'), (3, 'Romania', 'Rom.', 'ROU', 642, 237500.0, 21959278, 46.0, 25.0, 'eu', 'others', 3, 'Romania', 'Rom.', 'ROU', 642, 237500.0, 21959278, 46.0, 25.0, 'eu'), (3, 'Belarus', 'Bela.', 'BLR', 112, 207600.0, 9685000, 53.0, 28.0, 'eu', 'others', 3, 'Belarus', 'Bela.', 'BLR', 112, 207600.0, 9685000, 53.0, 28.0, 'eu'), (3, 'Greece', 'Grc.', 'GRC', 300, 131940.0, 11000000, 39.0, 22.0, 'eu', 'others', 3, 'Greece', 'Grc.', 'GRC', 300, 131940.0, 11000000, 39.0, 22.0, 'eu'), (3, 'Bulgaria', 'Blg.', 'BGR', 100, 110910.0, 7148785, 43.0, 25.0, 'eu', 'others', 3, 'Bulgaria', 'Blg.', 'BGR', 100, 110910.0, 7148785, 43.0, 25.0, 'eu'), (3, 'Iceland', 'Ice.', 'ISL', 352, 103000.0, 308910, 65.0, -18.0, 'eu', 'nordics', 3, 'Iceland', 'Ice.', 'ISL', 352, 103000.0, 308910, 65.0, -18.0, 'eu'), (3, 'Portugal', 'Port.', 'PRT', 620, 92391.0, 10676000, 39.5, -8.0, 'eu', 'others', 3, 'Portugal', 'Port.', 'PRT', 620, 92391.0, 10676000, 39.5, -8.0, 'eu'), (3, 'Czech Republic', 'Czech Rep.', 'CZE', 203, 78866.0, 10476000, 49.75, 15.0, 'eu', 'others', 3, 'Czech Republic', 'Czech Rep.', 'CZE', 203, 78866.0, 10476000, 49.75, 15.0, 'eu'), (3, 'Denmark', 'Den.', 'DNK', 208, 43094.0, 5484000, 56.0, 10.0, 'eu', 'nordics', 3, 'Denmark', 'Den.', 'DNK', 208, 43094.0, 5484000, 56.0, 10.0, 'eu'), (4, 'Hungary', 'Hung.', 'HUN', 348, 93030.0, 9930000, 47.0, 20.0, 'eu', 'others', 4, 'Hungary', 'Hung.', 'HUN', 348, 93030.0, 9930000, 47.0, 20.0, 'eu'), (4, 'Serbia', 'Serb.', 'SRB', 688, 88361.0, 7344847, 44.82, 20.46, 'eu', 'others', 4, 'Serbia', 'Serb.', 'SRB', 688, 88361.0, 7344847, 44.82, 20.46, 'eu'), (4, 'Austria', 'Aus.', 'AUT', 40, 83858.0, 8205000, 47.33, 13.33, 'eu', 'others', 4, 'Austria', 'Aus.', 'AUT', 40, 83858.0, 8205000, 47.33, 13.33, 'eu'), (4, 'Ireland', 'Ire.', 'IRL', 372, 70280.0, 4622917, 53.0, -8.0, 'eu', 'others', 4, 'Ireland', 'Ire.', 'IRL', 372, 70280.0, 4622917, 53.0, -8.0, 'eu'), (4, 'Lithuania', 'Lith.', 'LTU', 440, 65200.0, 3565000, 56.0, 24.0, 'eu', 'baltics', 4, 'Lithuania', 'Lith.', 'LTU', 440, 65200.0, 3565000, 56.0, 24.0, 'eu'), (4, 'Latvia', 'Lat.', 'LVA', 428, 64589.0, 2217969, 57.0, 25.0, 'eu', 'baltics', 4, 'Latvia', 'Lat.', 'LVA', 428, 64589.0, 2217969, 57.0, 25.0, 'eu'), (4, 'Croatia', 'Cro.', 'HRV', 191, 56542.0, 4491000, 45.17, 15.5, 'eu', 'others', 4, 'Croatia', 'Cro.', 'HRV', 191, 56542.0, 4491000, 45.17, 15.5, 'eu'), (4, 'Bosnia and Herzegovina', 'Bos.', 'BIH', 70, 51129.0, 4590000, 44.25, 17.83, 'eu', 'others', 4, 'Bosnia and Herzegovina', 'Bos.', 'BIH', 70, 51129.0, 4590000, 44.25, 17.83, 'eu'), (4, 'Slovakia', 'Slvk.', 'SVK', 703, 48845.0, 5455000, 48.67, 19.5, 'eu', 'others', 4, 'Slovakia', 'Slvk.', 'SVK', 703, 48845.0, 5455000, 48.67, 19.5, 'eu'), (4, 'Estonia', 'Est.', 'EST', 233, 45226.0, 1291170, 59.0, 26.0, 'eu', 'baltics', 4, 'Estonia', 'Est.', 'EST', 233, 45226.0, 1291170, 59.0, 26.0, 'eu'), (4, 'Netherlands', 'Neth.', 'NLD', 528, 41526.0, 16645000, 52.5, 5.75, 'eu', 'benelux', 4, 'Netherlands', 'Neth.', 'NLD', 528, 41526.0, 16645000, 52.5, 5.75, 'eu'), (4, 'Switzerland', 'Switz.', 'CHE', 756, 41290.0, 7581000, 47.0, 8.01, 'eu', 'others', 4, 'Switzerland', 'Switz.', 'CHE', 756, 41290.0, 7581000, 47.0, 8.01, 'eu'), (4, 'Moldova', 'Mol.', 'MDA', 498, 33843.0, 4324000, 47.0, 29.0, 'eu', 'others', 4, 'Moldova', 'Mol.', 'MDA', 498, 33843.0, 4324000, 47.0, 29.0, 'eu'), (4, 'Belgium', 'Bel.', 'BEL', 56, 30510.0, 10403000, 50.83, 4.0, 'eu', 'benelux', 4, 'Belgium', 'Bel.', 'BEL', 56, 30510.0, 10403000, 50.83, 4.0, 'eu'), (4, 'Albania', 'Alb.', 'ALB', 8, 28748.0, 2986952, 41.0, 20.0, 'eu', 'others', 4, 'Albania', 'Alb.', 'ALB', 8, 28748.0, 2986952, 41.0, 20.0, 'eu'), (4, 'Macedonia', 'Mac.', 'MKD', 807, 25333.0, 2061000, 41.83, 22.0, 'eu', 'others', 4, 'Macedonia', 'Mac.', 'MKD', 807, 25333.0, 2061000, 41.83, 22.0, 'eu'), (4, 'Slovenia', 'Slvn.', 'SVN', 705, 20273.0, 2007000, 46.25, 15.17, 'eu', 'others', 4, 'Slovenia', 'Slvn.', 'SVN', 705, 20273.0, 2007000, 46.25, 15.17, 'eu'), (4, 'Montenegro', 'Mont.', 'MNE', 499, 14026.0, 666730, 43.5, 19.3, 'eu', 'others', 4, 'Montenegro', 'Mont.', 'MNE', 499, 14026.0, 666730, 43.5, 19.3, 'eu'), (4, 'Cyprus', 'Cyp.', 'CYP', 196, 9250.0, 1102677, 35.0, 33.0, 'asia', 'others', 4, 'Cyprus', 'Cyp.', 'CYP', 196, 9250.0, 1102677, 35.0, 33.0, 'asia'), (4, 'Luxembourg', 'Lux.', 'LUX', 442, 2586.0, 497538, 49.75, 6.17, 'eu', 'benelux', 4, 'Luxembourg', 'Lux.', 'LUX', 442, 2586.0, 497538, 49.75, 6.17, 'eu'), (4, 'Faroe Is.', 'Far. Is.', 'FRO', 234, 1399.0, 48228, 62.0, -7.0, 'eu', 'others', 4, 'Faroe Is.', 'Far. Is.', 'FRO', 234, 1399.0, 48228, 62.0, -7.0, 'eu'), (4, 'Andorra', 'And.', 'AND', 20, 468.0, 84000, 42.5, 1.5, 'eu', 'others', 4, 'Andorra', 'And.', 'AND', 20, 468.0, 84000, 42.5, 1.5, 'eu'), (4, 'Malta', 'Malta', 'MLT', 470, 316.0, 403000, 35.92, 14.43, 'eu', 'others', 4, 'Malta', 'Malta', 'MLT', 470, 316.0, 403000, 35.92, 14.43, 'eu'), (4, 'Liechtenstein', 'Liech.', 'LIE', 438, 160.0, 35000, 47.17, 9.53, 'eu', 'others', 4, 'Liechtenstein', 'Liech.', 'LIE', 438, 160.0, 35000, 47.17, 9.53, 'eu'), (4, 'Guernsey', 'Guern.', 'GGY', 831, 78.0, 65228, 49.58, -2.33, 'eu', 'others', 4, 'Guernsey', 'Guern.', 'GGY', 831, 78.0, 65228, 49.58, -2.33, 'eu'), (4, 'San Marino', 'S. Mar.', 'SMR', 674, 61.2, 31477, 43.93, 12.42, 'eu', 'others', 4, 'San Marino', 'S. Mar.', 'SMR', 674, 61.2, 31477, 43.93, 12.42, 'eu'), (4, 'Gibraltar', 'Gib.', 'GIB', 292, 6.5, 27884, 36.13, -5.35, 'eu', 'others', 4, 'Gibraltar', 'Gib.', 'GIB', 292, 6.5, 27884, 36.13, -5.35, 'eu'), (4, 'Monaco', 'Monaco', 'MCO', 492, 2.0, 32965, 43.73, 7.42, 'eu', 'others', 4, 'Monaco', 'Monaco', 'MCO', 492, 2.0, 32965, 43.73, 7.42, 'eu'), (4, 'Vatican City', 'Vatican City', 'VAT', 336, 0.4, 921, 41.9, 12.45, 'eu', 'others', 4, 'Vatican City', 'Vatican City', 'VAT', 336, 0.4, 921, 41.9, 12.45, 'eu')]
<class 'list'>

In [18]:
query = """
    SELECT Code
    FROM countries
"""

result = dbCursor.execute(query).fetchall()
print(result)
print(type(result))

[('UKR',), ('FRA',), ('ESP',), ('SWE',), ('DEU',), ('FIN',), ('NOR',), ('POL',), ('ITA',), ('GBR',), ('ROU',), ('BLR',), ('GRC',), ('BGR',), ('ISL',), ('PRT',), ('CZE',), ('DNK',), ('HUN',), ('SRB',), ('AUT',), ('IRL',), ('LTU',), ('LVA',), ('HRV',), ('BIH',), ('SVK',), ('EST',), ('NLD',), ('CHE',), ('MDA',), ('BEL',), ('ALB',), ('MKD',), ('SVN',), ('MNE',), ('CYP',), ('LUX',), ('FRO',), ('AND',), ('MLT',), ('LIE',), ('GGY',), ('SMR',), ('GIB',), ('MCO',), ('VAT',)]
<class 'list'>

<h3>Exercise 2</h3>
<p>
    Gebruik SQL queries voor het verkrijgen van
<ol>
    <li>het aantal landen dat onderdeel is van de Nordics</li>
    <li>het aantal Europese landen dat lid is van de Europese Unie</li>
    <li>het aantal EU-landen dat deel uitmaakt van de Norics</li>
</ol>
</p>

In [19]:
# het aantal landen dat onderdeel is van de Nordics

dbCursor = dbConnection.cursor()

#To find the country names(distinct gives unique values and avoids duplicate values) within group name as nordics:

#query = """ 
   # SELECT distinct(name)
    #FROM countries 
   # WHERE groups = 'nordics'
   # """    
 

query = """ 
    SELECT count(1)
    FROM countries 
    WHERE groups = 'nordics'
    """       
aantalLandenResult = dbCursor.execute(query).fetchall()
print(aantalLandenResult)

[(4,)]

In [26]:
#  het aantal Europese landen dat lid is van de Europese Unie  
query = """ 
    SELECT count(*)
    FROM countries 
    WHERE continent = 'eu'
    """   
aantalEuLandenResult = dbCursor.execute(query).fetchall()
print(aantalEuLandenResult)

[(46,)]

In [25]:
#het aantal EU-landen dat deel uitmaakt van de Nordics

query = """ 
    SELECT count(*)
    FROM countries 
    WHERE continent = 'eu' AND groups = 'nordics'
    """   
aantalEuLandenNordics = dbCursor.execute(query).fetchall()
print(type(aantalEuLandenNordics))

<class 'list'>

In [27]:
# Close connection to SQLite database

dbConnection.close()