In [16]:
import os
from matplotlib import pyplot as plt
import pickle
from PIL import Image
import pandas as pd
import sqlite3
import json
import numpy as np
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf
import logging
import math

# Hardening
from pathlib import Path

In [17]:
testData = pd.read_csv('../Project/rest_api_netlify.csv')
display(testData)

        id  genetic  length  mass  exercise  smoking  alcohol  sugar  lifespan
0        1     84.0   180.0  90.0       2.0      9.0      1.0      2        86
1        2     84.0   204.0  79.0       3.0      2.0      7.0      3       100
2        3     84.0   174.0  74.0       3.0     20.0      3.0      2        87
3        4     84.0   187.0  78.0       2.0      6.0      5.0      3        91
4        5     84.0   187.0  89.0       2.0     12.0      0.0      2        83
...    ...      ...     ...   ...       ...      ...      ...    ...       ...
8187  8188     82.0   185.0  67.0       3.0     11.0      8.0      2        90
8188  8189     82.0   183.0  72.0       2.0      1.0      5.0      4        88
8189  8190     83.0   192.0  92.0       1.0     22.0      2.0      4        62
8190  8191     81.0   175.0  60.0       3.0     13.0      7.0      2        93
8191  8192     83.0   204.0  76.0       3.0      8.0      8.0      1        96

[8192 rows x 9 columns]

In [18]:
testData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8192 entries, 0 to 8191
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        8192 non-null   int64
 1   genetic   8191 non-null   float64
 2   length    8190 non-null   float64
 3   mass      8191 non-null   float64
 4   exercise  8191 non-null   float64
 5   smoking   8191 non-null   float64
 6   alcohol   8191 non-null   float64
 7   sugar     8192 non-null   int64
 8   lifespan  8192 non-null   int64
dtypes: float64(6), int64(3)
memory usage: 576.1 KB

In [19]:
testData = testData.dropna()
testData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8185 entries, 0 to 8191
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        8185 non-null   int64
 1   genetic   8185 non-null   float64
 2   length    8185 non-null   float64
 3   mass      8185 non-null   float64
 4   exercise  8185 non-null   float64
 5   smoking   8185 non-null   float64
 6   alcohol   8185 non-null   float64
 7   sugar     8185 non-null   int64
 8   lifespan  8185 non-null   int64
dtypes: float64(6), int64(3)
memory usage: 639.5 KB

In [20]:
testData = testData.dropna()
testData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8185 entries, 0 to 8191
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        8185 non-null   int64
 1   genetic   8185 non-null   float64
 2   length    8185 non-null   float64
 3   mass      8185 non-null   float64
 4   exercise  8185 non-null   float64
 5   smoking   8185 non-null   float64
 6   alcohol   8185 non-null   float64
 7   sugar     8185 non-null   int64
 8   lifespan  8185 non-null   int64
dtypes: float64(6), int64(3)
memory usage: 639.5 KB

In [21]:
testData['BMI'] = testData['mass'] / pow( (testData['length']/100), 2 )
display(testData)

,id,genetic,length,mass,exercise,smoking,alcohol,sugar,lifespan,BMI
0,1,84.0,180.0,90.0,2.0,9.0,1.0,2,86,27.777778
1,2,84.0,204.0,79.0,3.0,2.0,7.0,3,100,18.983083
2,3,84.0,174.0,74.0,3.0,20.0,3.0,2,87,24.441802
3,4,84.0,187.0,78.0,2.0,6.0,5.0,3,91,22.305471
4,5,84.0,187.0,89.0,2.0,12.0,0.0,2,83,25.451114
...,...,...,...,...,...,...,...,...,...,...
8187,8188,82.0,185.0,67.0,3.0,11.0,8.0,2,90,19.576333
8188,8189,82.0,183.0,72.0,2.0,1.0,5.0,4,88,21.499597
8189,8190,83.0,192.0,92.0,1.0,22.0,2.0,4,62,24.956597
8190,8191,81.0,175.0,60.0,3.0,13.0,7.0,2,93,19.591837
8191,8192,83.0,204.0,76.0,3.0,8.0,8.0,1,96,18.262207

In [22]:
from sklearn import preprocessing, svm

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

# loading library
#import pickle

# Separating the data into independent and dependent variables

#

X = testData[['genetic', 'exercise', 'smoking', 'alcohol', 'sugar', 'BMI']]

y = testData['lifespan']

# Splitting the data into training and testing data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

regr = LinearRegression()

regr.fit(X_train, y_train)

print(regr.score(X_test, y_test))

# Data scatter of predicted values

y_pred = regr.predict(X_test)
print(y_pred)

#y_predict = regr.predict([[80, 4, 2, 2, 25]])
#print(y_predict)


regCoef = regr.coef_
print(regCoef)
regInter = regr.intercept_


print('mean_squared_error : ', mean_squared_error(y_test, y_pred))
print('mean_absolute_error : ', mean_absolute_error(y_test, y_pred))

0.9294988678441257
[96.83634144 74.41522716 77.17306437 ... 79.05417219 68.88943398
 71.39144555]
[ 0.93463091  8.80522145 -0.80119272 -0.89943073 -2.8806774  -0.59264141]
mean_squared_error :  8.16238064846819
mean_absolute_error :  2.38533724681856

In [23]:
with open('model_test', 'wb') as files:
    pickle.dump(regr, files)

In [24]:
import pickle

with open('model_test' , 'rb') as f:
    lr = pickle.load(f)

In [25]:
import logging
import pandas as pd
import pickle
import statsmodels as sm
import statsmodels.formula.api as smf
import sqlite3

# Global configuration
logging.basicConfig(level=logging.DEBUG)
regModel = '../Project/model_test'

def predict(inputData):
    logging.info("Load model")
    
    with open(model_test , 'rb') as f:
        lr = pickle.load(f)
    
    # Predict lifespan with regressor and inputData
    return predict

# TODO Create an interface for all input variables
# def interface():
    
def inputDigit(message, acceptableRange):
    inputStr = str()
    withinRange = False
    numberOfTries = 3
    i = 0

    while not (inputStr.isdigit() and withinRange) and i < numberOfTries:
        inputStr = input(message)

        if inputStr.isdigit():
            inputNum = float(inputStr)

            if inputNum in acceptableRange:
                return inputNum

        i += 1

# acceptableRange = range(18, 118)
# age = int(inputDigit("Age [18 - 118]: ", acceptableRange))
# logging.debug(f"age : {age}")

In [26]:
# Imports for Interface
import tkinter
from tkinter import *
from tkinter import ttk
from PIL import ImageTk, Image
from tkinter import filedialog
import os

# Variables- for interface
def calculate(*args):
    try:
        g1 = float(genetic.get())
        len1 = float(length.get())
        mas1 = float(weigth.get())
        ex1 = float(exercise.get())
        sm1 = float(smoking.get())
        al1 = float(alcohol.get())
        su1 = float(sugar.get())
        bm1 = (mas1)/((len1/100)**2)
        lifespan_advis.set(int((regCoef[0] * g1)+(regCoef[1] * ex1)+(regCoef[2] * sm1)+(regCoef[3] * al1)+(regCoef[4] * su1)+ (regCoef[5] * bm1)+regInter))
        bmi1.set(int(bm1))
    except ValueError:
        pass

In [27]:
# Building interface
root = Tk()
root.title("lifespan")
    
mainframe = ttk.Frame(root, padding="3 3 12 12")
mainframe.grid(column=0, row=0, sticky=(N, W, E, S))
root.columnconfigure(0, weight=1)
root.rowconfigure(0, weight=1)

genetic = StringVar()
genetic_entry = ttk.Entry(mainframe, width=22, textvariable=genetic)
genetic_entry.grid(column=1, row=2, sticky=(W, E))

length = StringVar()
length_entry = ttk.Entry(mainframe, width=22, textvariable=length)
length_entry.grid(column=2, row=2, sticky=(W, E))

weigth = StringVar()
weigth_entry = ttk.Entry(mainframe, width=22, textvariable=weigth)
weigth_entry.grid(column=3, row=2, sticky=(W, E))

exercise = StringVar()
exercise_entry = ttk.Entry(mainframe, width=22, textvariable=exercise)
exercise_entry.grid(column=4, row=2, sticky=(W, E))

smoking = StringVar()
smoking_entry = ttk.Entry(mainframe, width=22, textvariable=smoking)
smoking_entry.grid(column=5, row=2, sticky=(W, E))

alcohol = StringVar()
alcohol_entry = ttk.Entry(mainframe, width=22, textvariable=alcohol)
alcohol_entry.grid(column=6, row=2, sticky=(W, E))

sugar = StringVar()
sugar_entry = ttk.Entry(mainframe, width=22, textvariable=sugar)
sugar_entry.grid(column=7, row=2, sticky=(W, E))

In [28]:
bmi1 = StringVar()
ttk.Label(mainframe, textvariable=bmi1).grid(column=8, row=2, sticky=(W, E))

lifespan_advis = StringVar()
ttk.Label(mainframe, textvariable=lifespan_advis).grid(column=9, row=2, sticky=(W, E))

ttk.Button(mainframe, text="Chart", command=calculate).grid(column=1, row=3, sticky=W)
ttk.Button(mainframe, text="Chart", command=calculate).grid(column=2, row=3, sticky=W)
ttk.Button(mainframe, text="Chart", command=calculate).grid(column=3, row=3, sticky=W)
ttk.Button(mainframe, text="Chart", command=calculate).grid(column=4, row=3, sticky=W)
ttk.Button(mainframe, text="Chart", command=calculate).grid(column=5, row=3, sticky=W)
ttk.Button(mainframe, text="Chart", command=calculate).grid(column=6, row=3, sticky=W)
ttk.Button(mainframe, text="Chart", command=calculate).grid(column=7, row=3, sticky=W)
ttk.Button(mainframe, text="Chart", command=calculate).grid(column=8, row=3, sticky=W)
ttk.Button(mainframe, text="Calculate", command=calculate).grid(column=10, row=3, sticky=W)

ttk.Label(mainframe, text="Your genetic in years").grid(column=1, row=1, sticky=W)
ttk.Label(mainframe, text="Your length in cm").grid(column=2, row=1, sticky=W)
ttk.Label(mainframe, text="Your weigth in kg").grid(column=3, row=1, sticky=W)
ttk.Label(mainframe, text="Hours of exercise per week").grid(column=4, row=1, sticky=W)
ttk.Label(mainframe, text="Cigarettes per day").grid(column=5, row=1, sticky=W)
ttk.Label(mainframe, text="Glasses alcohol per day").grid(column=6, row=1, sticky=W)
ttk.Label(mainframe, text="Cubes of sugar per day").grid(column=7, row=1, sticky=W)
ttk.Label(mainframe, text="Your BMI is").grid(column=8, row=1, sticky=W)
ttk.Label(mainframe, text="Your lifespan prognosis").grid(column=9, row=1, sticky=W)
ttk.Label(mainframe, text="years").grid(column=9, row=3, sticky=W)

In [29]:
# Interface INPUT loop
for child in mainframe.winfo_children():
    child.grid_configure(padx=0, pady=0)

genetic_entry.focus()
length_entry.focus()
weigth_entry.focus()
exercise_entry.focus()
smoking_entry.focus()
alcohol_entry.focus()
sugar_entry.focus()
root.bind("<Return>", calculate)

root.mainloop()